plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pbuchman.duduhome'
    compileSdk 36

    defaultConfig {
        applicationId 'com.pbuchman.duduhome'
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName '0.5.2-local'
        testInstrumentationRunner 'com.pbuchman.duduhome.SafetyChecks'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
    }
}
